# Generated by Django 4.2.8 on 2023-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="user",
            field=models.CharField(max_length=255),
        ),
    ]
